name: Build resume

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true


    - name: Download fonts
      run: |
        curl -O https://moji.or.jp/wp-content/ipafont/IPAexfont/IPAexfont00401.zip
        unzip -o IPAexfont00401.zip
        mv IPAexfont00401/* fonts/
        rm -rf IPAexfont00401
        rm -f IPAexfont00401.zip

    - name: Build
      run: |
        mkdir dist
        ruby make_cv.rb -i data.yaml -s style.txt -o dist/output.pdf

    - name: Deploy gh page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
